// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvnfWnORBlpnRKdGSVBUuna9yIFKp8f2w',
    appId: '1:376353503362:web:65d3fb1f8fb4b14cf99c9b',
    messagingSenderId: '376353503362',
    projectId: 'flutter-chat-app-e9f06',
    authDomain: 'flutter-chat-app-e9f06.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e9f06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADyOSsHo4sOBKcSSJGIetSCzezrHzNAsM',
    appId: '1:376353503362:android:93b6ccc511ac44f7f99c9b',
    messagingSenderId: '376353503362',
    projectId: 'flutter-chat-app-e9f06',
    storageBucket: 'flutter-chat-app-e9f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEBY7TATuuPOM_DTlgEbUNeO1El3bIBCs',
    appId: '1:376353503362:ios:a372dc78058f7be1f99c9b',
    messagingSenderId: '376353503362',
    projectId: 'flutter-chat-app-e9f06',
    storageBucket: 'flutter-chat-app-e9f06.appspot.com',
    iosBundleId: 'com.example.chatappRealtimeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEBY7TATuuPOM_DTlgEbUNeO1El3bIBCs',
    appId: '1:376353503362:ios:a372dc78058f7be1f99c9b',
    messagingSenderId: '376353503362',
    projectId: 'flutter-chat-app-e9f06',
    storageBucket: 'flutter-chat-app-e9f06.appspot.com',
    iosBundleId: 'com.example.chatappRealtimeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvnfWnORBlpnRKdGSVBUuna9yIFKp8f2w',
    appId: '1:376353503362:web:c2bc537cfb841dddf99c9b',
    messagingSenderId: '376353503362',
    projectId: 'flutter-chat-app-e9f06',
    authDomain: 'flutter-chat-app-e9f06.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e9f06.appspot.com',
  );
}
